
name: Tests

on:
  pull_request:
  workflow_dispatch:
  workflow_call:

jobs:
  pytest:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.11"]
        os: [ubuntu-latest, macOS-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Set up PDM
        uses: pdm-project/setup-pdm@v3
        with:
          python-version: ${{ matrix.python-version }}
          cache: true

      - name: Install dependencies
        run: |
          pdm sync -d

      - name: Run pytest
        run: |
          pdm test

  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up PDM
        uses: pdm-project/setup-pdm@v3
        with:
          python-version: "3.11"
          cache: true

      - name: Install dependencies
        run: |
          pdm sync -d

      - name: Run ruff
        run: |
          pdm lint

  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up PDM
        uses: pdm-project/setup-pdm@v3
        with:
          python-version: "3.11"
          cache: true

      - name: Install dependencies
        run: |
          pdm sync -d

      - name: Run mypy
        run: |
          pdm typecheck

  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up PDM
        uses: pdm-project/setup-pdm@v3
        with:
          python-version: "3.11"
          cache: true

      - name: Install dependencies
        run: |
          pdm sync -d

      - name: Run black
        run: |
          pdm format:check
